### ISSUE TITLE
mv refuse to rename a directory to another directory if the target directory contains files. 

### ISSUE THREAD

**Issue by jazio** [ec-europa/cloud9#70]
mv refuse to rename a directory to another directory if the target directory contains files. 

This is normal in your case because you turn out to want to merge the content of the source into the target, which mv will not do.

Therefore the script run into:
`mv: cannot move ‘temp/lib’ to ‘./lib’: Directory not empty
rmdir: failed to remove ‘temp/’: Directory not empty
/home/ec2-user/environment/cloud9/lib/install.sh: line 42: cd: /health-reference: No such file or directory`

**Comment by secobau** [comment]
This is not an issue. It is just a warning. Normal behavior. If the folder is empty it is okay. If not then it complains. Nothing to worry about.

**Comment by secobau** [comment]
I have just successfully cloned HEALTH in Cloud9 environment:
`BUILD FINISHED

Total time: 3 minutes  9.74 seconds
`
The script works fine.
If you have any issue then it is because of some other reason.
Thank you very much.
