### ISSUE TITLE
What is the reason for using version 3 in docker-compose files

### ISSUE THREAD

**Issue by secobau** [ec-europa/cloud9#77]
What is the reason for using version 3 in docker-compose files?
https://github.com/ec-europa/cloud9/tree/master/salt/docker/files/docker-compose

Version 3 is better oriented for using docker in swarm mode and version 2 is better oriented for using docker as a standalone node.

Version 3 lacks some of the features still available in version 2.

Unless there is a specific feature of docker-compose in version 3 that we need to use then I would recommend to use version 2.

Otherwise I would recommend to use version 3 and docker in swarm mode.

**Comment by secobau** [comment]
> We use the latest and recommended version that provided cross-compatiblity, so the provided yml file works for docker-compose and swarm. The user have the choise to work with swarm or docker-compose (on the doc, we have the example for the both usage: docker-compose and docker stack)

Well that is not correct IMHO. Where is this recommended? I have this other feedback from Docker:
https://github.com/docker/compose/issues/4305#issuecomment-305378202

> Which features we need are missing ?

I do not know whether you need them but for example the condition from depends_on:
```
version: '2.1'
services:
 web:
  build: .
  depends_on:
   db:
    condition: service_healthy
   redis:
    condition: service_started
 redis:
  image: redis
 db:
  image: redis
  healthcheck:
   test: "exit 0"
```
In the above example, Compose waits for the redis service to be started (legacy behavior) and the db service to be healthy before starting web.

> We already use version 3. And we don't want force developer to use swarm instead of docker-compose, better to leave the choice to the user.

Docker swarm and docker-compose are different paradigms. It is difficult to recommend one over the other. Nevertheless docker-compose will be discontinued. And it is good to get used to docker swarm since it is the coming future:
https://github.com/docker/compose/issues/4305#issuecomment-276527457

But if you are using docker-compose there is no point in using version 3 for the compose file (as stated by Docker in the first of the links I have shared).

I think that using version 3 in docker-compose has all the disadvantages and none of the advantages.
That is why I asked whether there was a specific reason to use it instead of version 2.

**Comment by gervasek** [comment]
> Well that is not correct IMHO. Where is this recommended?

I already replied to this on my previous comment, it's on docs.docker.com: https://docs.docker.com/compose/compose-file/compose-versioning : "[...] the **latest** and **recommended** version, designed to be cross-compatible between Compose and the Docker Engine’s swarm mode."

> And it is good to get used to docker swarm since it is the coming future

We don't want force developer to use swarm instead of docker-compose, better to leave the choice to the user.

Version 3 is compatible with docker-compose and docker swarn, there is no reason to back to 2.
