### ISSUE TITLE
Need an upgrade to min php71

### ISSUE THREAD

**Issue by jazio** [ec-europa/cloud9#81]
There is no option to use PHP 7.1+

unless you run 

```
sudo yum remove php*
sudo yum install php71 php71-gd php71-imap php71-mbstring php71-mysqlnd php71-opcache php71-pdo php71-pecl-apcu```

**Comment by gervasek** [comment]
PHP version can be defined using pillar. It's described on wikis page "4. Configure C9".
Example:
`sudo salt-call state.apply profiles.lamp pillar='{"php-fpm":{"version":"71"}}'`
